import { describe, expect, it } from 'vitest';
import {
  extractVideoId,
  detectYouTubeUrls,
  hasYouTubeUrl,
  formatTranscriptForContext,
  formatTranscriptWithTimestamps,
  isTranscriptError,
  type TranscriptResult,
  type TranscriptError,
} from '../lib/youtube-transcript';

describe('extractVideoId', () => {
  it('extracts from standard watch URL', () => {
    expect(extractVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from short URL', () => {
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from embed URL', () => {
    expect(extractVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from shorts URL', () => {
    expect(extractVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from live URL', () => {
    expect(extractVideoId('https://www.youtube.com/live/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from mobile URL', () => {
    expect(extractVideoId('https://m.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from URL with extra params', () => {
    expect(extractVideoId('https://www.youtube.com/watch?list=PLxyz&v=dQw4w9WgXcQ&t=42s')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from URL without protocol', () => {
    expect(extractVideoId('youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts bare video ID', () => {
    expect(extractVideoId('dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('rejects invalid video IDs', () => {
    expect(extractVideoId('not-a-valid-id')).toBeNull();
    expect(extractVideoId('https://example.com')).toBeNull();
    expect(extractVideoId('')).toBeNull();
    expect(extractVideoId('abc')).toBeNull();
  });

  it('rejects IDs with invalid characters', () => {
    expect(extractVideoId('dQw4w9WgXc!')).toBeNull();
  });

  it('handles v/ URL format', () => {
    expect(extractVideoId('https://www.youtube.com/v/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });
});

describe('detectYouTubeUrls', () => {
  it('finds single URL in text', () => {
    expect(detectYouTubeUrls('Check this video https://www.youtube.com/watch?v=abc12345678')).toEqual(['abc12345678']);
  });

  it('finds multiple URLs in text', () => {
    const ids = detectYouTubeUrls('Compare https://youtu.be/abc12345678 and https://youtu.be/xyz98765432');
    expect(ids).toHaveLength(2);
    expect(ids).toContain('abc12345678');
    expect(ids).toContain('xyz98765432');
  });

  it('deduplicates same video ID', () => {
    const ids = detectYouTubeUrls('https://youtu.be/abc12345678 and https://www.youtube.com/watch?v=abc12345678');
    expect(ids).toEqual(['abc12345678']);
  });

  it('returns empty for text without YouTube URLs', () => {
    expect(detectYouTubeUrls('Just some normal text here')).toEqual([]);
    expect(detectYouTubeUrls('Check https://example.com')).toEqual([]);
  });

  it('handles mixed content with YouTube and non-YouTube URLs', () => {
    const ids = detectYouTubeUrls('See https://example.com and https://youtu.be/abc12345678 and https://google.com');
    expect(ids).toEqual(['abc12345678']);
  });
});

describe('hasYouTubeUrl', () => {
  it('returns true for YouTube watch URL', () => {
    expect(hasYouTubeUrl('Check https://www.youtube.com/watch?v=abc12345678')).toBe(true);
  });

  it('returns true for youtu.be URL', () => {
    expect(hasYouTubeUrl('Check https://youtu.be/abc12345678')).toBe(true);
  });

  it('returns true for shorts URL', () => {
    expect(hasYouTubeUrl('https://www.youtube.com/shorts/abc12345678')).toBe(true);
  });

  it('returns false for non-YouTube text', () => {
    expect(hasYouTubeUrl('Just some text')).toBe(false);
    expect(hasYouTubeUrl('https://example.com')).toBe(false);
  });
});

describe('isTranscriptError', () => {
  it('identifies error results', () => {
    const err: TranscriptError = { videoId: 'test', error: 'No captions', code: 'NO_CAPTIONS' };
    expect(isTranscriptError(err)).toBe(true);
  });

  it('identifies success results', () => {
    const ok: TranscriptResult = {
      videoId: 'test',
      title: 'Test Video',
      segments: [{ text: 'Hello', start: 0, duration: 1 }],
      fullText: 'Hello',
      language: 'en',
      isAutoGenerated: false,
    };
    expect(isTranscriptError(ok)).toBe(false);
  });
});

describe('formatTranscriptForContext', () => {
  const result: TranscriptResult = {
    videoId: 'abc12345678',
    title: 'Test Video',
    segments: [
      { text: 'Hello world', start: 0, duration: 2 },
      { text: 'This is a test', start: 2, duration: 3 },
    ],
    fullText: 'Hello world This is a test',
    language: 'en',
    isAutoGenerated: false,
  };

  it('includes title and video ID', () => {
    const formatted = formatTranscriptForContext(result);
    expect(formatted).toContain('Test Video');
    expect(formatted).toContain('abc12345678');
  });

  it('includes full text', () => {
    const formatted = formatTranscriptForContext(result);
    expect(formatted).toContain('Hello world This is a test');
  });

  it('marks auto-generated transcripts', () => {
    const auto = { ...result, isAutoGenerated: true };
    const formatted = formatTranscriptForContext(auto);
    expect(formatted).toContain('auto-generated');
  });

  it('omits auto-generated tag for manual captions', () => {
    const formatted = formatTranscriptForContext(result);
    expect(formatted).not.toContain('auto-generated');
  });
});

describe('formatTranscriptWithTimestamps', () => {
  const result: TranscriptResult = {
    videoId: 'abc12345678',
    title: 'Test Video',
    segments: [
      { text: 'Intro', start: 0, duration: 5 },
      { text: 'Main point', start: 65, duration: 10 },
      { text: 'Conclusion', start: 3661, duration: 5 },
    ],
    fullText: 'Intro Main point Conclusion',
    language: 'en',
    isAutoGenerated: true,
  };

  it('formats timestamps as MM:SS', () => {
    const formatted = formatTranscriptWithTimestamps(result);
    expect(formatted).toContain('[00:00] Intro');
    expect(formatted).toContain('[01:05] Main point');
    expect(formatted).toContain('[61:01] Conclusion');
  });

  it('includes header with metadata', () => {
    const formatted = formatTranscriptWithTimestamps(result);
    expect(formatted).toContain('Test Video');
    expect(formatted).toContain('auto-generated');
  });
});
