/**
 * YouTube transcript extraction via innertube captions API.
 * Zero dependencies — pure fetch against YouTube's public endpoints.
 * No API key required.
 */

const YT_URL_PATTERNS = [
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?(?:[^&]*&)*v=([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/live\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?youtu\.be\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?(?:www\.)?youtube\.com\/v\/([a-zA-Z0-9_-]{11})/,
  /(?:https?:\/\/)?m\.youtube\.com\/watch\?(?:[^&]*&)*v=([a-zA-Z0-9_-]{11})/,
];

const YT_URL_DETECT = /(?:youtube\.com\/(?:watch|embed|shorts|live|v\/)|youtu\.be\/)/i;

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptResult {
  videoId: string;
  title: string;
  segments: TranscriptSegment[];
  fullText: string;
  language: string;
  isAutoGenerated: boolean;
}

export interface TranscriptError {
  videoId: string;
  error: string;
  code: 'NO_CAPTIONS' | 'VIDEO_UNAVAILABLE' | 'FETCH_FAILED' | 'PARSE_ERROR';
}

export function extractVideoId(input: string): string | null {
  const trimmed = input.trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) return trimmed;
  for (const pattern of YT_URL_PATTERNS) {
    const match = trimmed.match(pattern);
    if (match?.[1]) return match[1];
  }
  return null;
}

export function detectYouTubeUrls(text: string): string[] {
  const ids = new Set<string>();
  const urlRegex = /https?:\/\/[^\s<>"{}|\\^`\[\]]+/g;
  let match: RegExpExecArray | null;
  while ((match = urlRegex.exec(text)) !== null) {
    if (YT_URL_DETECT.test(match[0])) {
      const id = extractVideoId(match[0]);
      if (id) ids.add(id);
    }
  }
  return [...ids];
}

export function hasYouTubeUrl(text: string): boolean {
  return YT_URL_DETECT.test(text);
}

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)));
}

function parseTimedText(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const tagRegex = /<text\s+start="([^"]*)"(?:\s+dur="([^"]*)")?[^>]*>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;
  while ((match = tagRegex.exec(xml)) !== null) {
    const start = parseFloat(match[1]) || 0;
    const duration = parseFloat(match[2] || '0');
    const rawText = match[3] || '';
    const text = decodeHtmlEntities(rawText.replace(/<[^>]+>/g, '')).trim();
    if (text) {
      segments.push({ text, start, duration });
    }
  }
  return segments;
}

function segmentsToFullText(segments: TranscriptSegment[]): string {
  const lines: string[] = [];
  let currentLine = '';
  for (const seg of segments) {
    const next = currentLine ? `${currentLine} ${seg.text}` : seg.text;
    if (next.length > 120 && currentLine) {
      lines.push(currentLine);
      currentLine = seg.text;
    } else {
      currentLine = next;
    }
  }
  if (currentLine) lines.push(currentLine);
  return lines.join('\n');
}

function extractPlayerResponse(html: string): any | null {
  const patterns = [
    /var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;/,
    /ytInitialPlayerResponse\s*=\s*(\{.+?\})\s*;/,
  ];
  for (const pat of patterns) {
    const m = html.match(pat);
    if (m?.[1]) {
      try { return JSON.parse(m[1]); } catch {}
    }
  }
  return null;
}

function extractVideoTitle(html: string): string {
  const m = html.match(/<title>([^<]*)<\/title>/);
  if (m?.[1]) {
    const raw = decodeHtmlEntities(m[1]).replace(/ - YouTube$/, '').trim();
    if (raw) return raw;
  }
  return 'Untitled video';
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
}

function pickBestTrack(tracks: CaptionTrack[], preferLang = 'en'): CaptionTrack | null {
  if (!tracks.length) return null;
  const manual = tracks.filter(t => t.kind !== 'asr');
  const auto = tracks.filter(t => t.kind === 'asr');
  const findByLang = (list: CaptionTrack[], lang: string) =>
    list.find(t => t.languageCode === lang) ||
    list.find(t => t.languageCode.startsWith(lang + '-'));

  return findByLang(manual, preferLang)
    || manual[0]
    || findByLang(auto, preferLang)
    || auto[0]
    || null;
}

export async function fetchTranscript(
  videoId: string,
  options: { preferLang?: string; timeoutMs?: number } = {},
): Promise<TranscriptResult | TranscriptError> {
  const { preferLang = 'en', timeoutMs = 8000 } = options;
  const url = `https://www.youtube.com/watch?v=${videoId}`;

  let html: string;
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), timeoutMs);
    const res = await fetch(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
      },
      signal: ctrl.signal,
    });
    clearTimeout(timer);
    if (!res.ok) {
      return { videoId, error: `YouTube returned HTTP ${res.status}`, code: 'FETCH_FAILED' };
    }
    html = await res.text();
  } catch (e: any) {
    return { videoId, error: e?.message || 'Network error', code: 'FETCH_FAILED' };
  }

  if (html.includes('Video unavailable') && !html.includes('ytInitialPlayerResponse')) {
    return { videoId, error: 'Video is unavailable or private', code: 'VIDEO_UNAVAILABLE' };
  }

  const playerResponse = extractPlayerResponse(html);
  if (!playerResponse) {
    return { videoId, error: 'Could not extract player data', code: 'PARSE_ERROR' };
  }

  const tracks: CaptionTrack[] =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];

  if (!tracks.length) {
    return { videoId, error: 'No captions available for this video', code: 'NO_CAPTIONS' };
  }

  const track = pickBestTrack(tracks, preferLang);
  if (!track) {
    return { videoId, error: 'No suitable caption track found', code: 'NO_CAPTIONS' };
  }

  let xml: string;
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), timeoutMs);
    const res = await fetch(track.baseUrl, { signal: ctrl.signal });
    clearTimeout(timer);
    if (!res.ok) {
      return { videoId, error: `Caption fetch returned HTTP ${res.status}`, code: 'FETCH_FAILED' };
    }
    xml = await res.text();
  } catch (e: any) {
    return { videoId, error: e?.message || 'Caption fetch failed', code: 'FETCH_FAILED' };
  }

  const segments = parseTimedText(xml);
  if (!segments.length) {
    return { videoId, error: 'Caption track was empty', code: 'NO_CAPTIONS' };
  }

  const title = extractVideoTitle(html);
  const isAutoGenerated = track.kind === 'asr';

  return {
    videoId,
    title,
    segments,
    fullText: segmentsToFullText(segments),
    language: track.languageCode,
    isAutoGenerated,
  };
}

export function isTranscriptError(r: TranscriptResult | TranscriptError): r is TranscriptError {
  return 'error' in r && 'code' in r;
}

export function formatTranscriptForContext(result: TranscriptResult): string {
  const autoTag = result.isAutoGenerated ? ' (auto-generated)' : '';
  const header = `YouTube Video Transcript: "${result.title}"\nVideo ID: ${result.videoId} | Language: ${result.language}${autoTag}\n`;
  const divider = '─'.repeat(40);
  return `${header}${divider}\n${result.fullText}\n${divider}`;
}

export function formatTranscriptWithTimestamps(result: TranscriptResult): string {
  const autoTag = result.isAutoGenerated ? ' (auto-generated)' : '';
  const header = `YouTube Video Transcript: "${result.title}"\nVideo ID: ${result.videoId} | Language: ${result.language}${autoTag}\n`;
  const divider = '─'.repeat(40);
  const lines = result.segments.map(seg => {
    const mins = Math.floor(seg.start / 60);
    const secs = Math.floor(seg.start % 60);
    const ts = `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
    return `[${ts}] ${seg.text}`;
  });
  return `${header}${divider}\n${lines.join('\n')}\n${divider}`;
}
