import type { APIRoute } from 'astro';
import { apiError, createRequestId, jsonResponse } from '../../lib/api-response';
import { checkCSRF } from '../../lib/csrf';
import {
  extractVideoId,
  fetchTranscript,
  isTranscriptError,
  formatTranscriptForContext,
} from '../../lib/youtube-transcript';
import { startCleanupInterval } from '../../lib/runtime-interval';

const RATE_WINDOW = 60_000;
const MAX_PER_MINUTE = 10;
const MAX_DAILY = 200;
const MAX_BODY = 2048;

const rateLimits = new Map<string, { count: number; reset: number }>();
const dailyCounts = new Map<string, number>();
let dailyReset = Date.now() + 86400000;

if (typeof setInterval !== 'undefined') {
  startCleanupInterval(() => {
    const now = Date.now();
    for (const [k, v] of rateLimits) { if (now > v.reset) rateLimits.delete(k); }
    if (now > dailyReset) { dailyCounts.clear(); dailyReset = now + 86400000; }
  }, 60_000);
}

function checkRate(ip: string): boolean {
  const now = Date.now();
  const e = rateLimits.get(ip);
  if (!e || now > e.reset) { rateLimits.set(ip, { count: 1, reset: now + RATE_WINDOW }); return true; }
  if (e.count >= MAX_PER_MINUTE) return false;
  e.count++;
  return true;
}

export const GET: APIRoute = async () =>
  apiError({ requestId: createRequestId(), status: 405, code: 'METHOD_NOT_ALLOWED', message: 'Use POST.' });

export const POST: APIRoute = async ({ request }) => {
  const rid = createRequestId();

  if (!checkCSRF(request)) {
    return apiError({ requestId: rid, status: 403, code: 'FORBIDDEN', message: 'Origin not allowed.' });
  }

  const ip = request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for') || 'unknown';

  if (!checkRate(ip)) {
    return apiError({ requestId: rid, status: 429, code: 'RATE_LIMITED', message: 'Too many transcript requests. Wait a moment.', retryable: true, retryAfter: 30 });
  }

  const dc = (dailyCounts.get(ip) || 0) + 1;
  dailyCounts.set(ip, dc);
  if (dc > MAX_DAILY) {
    return apiError({ requestId: rid, status: 429, code: 'DAILY_LIMIT', message: 'Daily transcript limit reached.' });
  }

  if (Number(request.headers.get('content-length') || '0') > MAX_BODY) {
    return apiError({ requestId: rid, status: 413, code: 'BODY_TOO_LARGE', message: 'Request too large.' });
  }

  let body: any;
  try {
    body = await request.json();
  } catch {
    return apiError({ requestId: rid, status: 400, code: 'INVALID_JSON', message: 'Invalid JSON body.' });
  }

  const url = body?.url || body?.videoId || '';
  const videoId = extractVideoId(String(url));
  if (!videoId) {
    return apiError({ requestId: rid, status: 400, code: 'INVALID_URL', message: 'Could not extract a YouTube video ID from the provided URL.' });
  }

  const result = await fetchTranscript(videoId, { preferLang: body?.lang || 'en' });

  if (isTranscriptError(result)) {
    return jsonResponse({
      success: false,
      videoId: result.videoId,
      error: result.error,
      code: result.code,
    }, { requestId: rid, status: 200 });
  }

  return jsonResponse({
    success: true,
    videoId: result.videoId,
    title: result.title,
    language: result.language,
    isAutoGenerated: result.isAutoGenerated,
    segmentCount: result.segments.length,
    transcript: result.fullText,
    contextBlock: formatTranscriptForContext(result),
  }, { requestId: rid });
};
